networks:
  project_network:
    external: true
    name: project_network

services:
  consul:
    image: hashicorp/consul:1.19.0
    container_name: consul.local
    restart: unless-stopped
    networks:
      - project_network
    ports:
      - "8500:8500"      # HTTP API & UI
      - "8600:8600/tcp"  # DNS
      - "8600:8600/udp"  # DNS
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: |
        {
          "skip_leave_on_interrupt": true,
          "datacenter": "dc1",
          "log_level": "INFO",
          "server": true,
          "ui_config": {
            "enabled": true
          }
        }
    command: >
      agent
      -server
      -bootstrap-expect=1
      -ui
      -bind=0.0.0.0
      -client=0.0.0.0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - consul-data:/consul/data

volumes:
  consul-data:
    name: consul-data

# docker network list
# docker network create project_network
# docker network inspect project_network

#docker save -o config-service-app-1.0.0.tar config-service-app:1.0.0
#docker load -i config-service-app-1.0.0.tar
