version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.19.0
    container_name: consul.local
    restart: always
    networks:
      - project_network
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "skip_leave_on_interrupt": true
        }
    # command: agent -server -bind=0.0.0.0 -bootstrap-expect=1
    command: agent -server -bootstrap -client="0.0.0.0" -advertise="127.0.0.1" -ui
    # command: agent -server -bootstrap-expect=1 -ui -bind="0.0.0.0"

networks:
    project_network:
        external: true
# $ docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' consul agent -server -bind=<external ip> -retry-join=<root agent ip> -bootstrap-expect=<number of server agents>

# docker network list
# docker network create project_network
# docker network inspect project_network

#docker save -o config-service-app-1.0.0.tar config-service-app:1.0.0
#docker load -i config-service-app-1.0.0.tar
